"""initial

Revision ID: fcda379556a4
Revises: 
Create Date: 2026-09-28 14:20:55.717458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcda379556a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(), nullable=False, comment="User's email address (must be unique)"),
    sa.Column('name', sa.String(), nullable=False, comment="User's full name"),
    sa.Column('password', sa.String(), nullable=False, comment='Hashed password'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the user account is active'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='References the user who created this record'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was updated'),
    sa.Column('updater_id', sa.Integer(), nullable=True, comment='References the user who last updated this record'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when this record was deleted'),
    sa.Column('deleter_id', sa.Integer(), nullable=True, comment='References the user who deleted this record'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('auth_token',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='References the user who created this record'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_auth_token_id'), 'auth_token', ['id'], unique=False)
    op.create_table('day',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('written_primary', sa.Text(), nullable=True, comment="'Felt like me' on a normal day, 'what happened' on a hard day"),
    sa.Column('written_drift', sa.Text(), nullable=True, comment="'Felt like drifting' — shown on both normal and hard days"),
    sa.Column('is_hard_day', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='References the user who created this record'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was updated'),
    sa.Column('updater_id', sa.Integer(), nullable=True, comment='References the user who last updated this record'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when this record was deleted'),
    sa.Column('deleter_id', sa.Integer(), nullable=True, comment='References the user who deleted this record'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_day_user_date')
    )
    op.create_index(op.f('ix_day_id'), 'day', ['id'], unique=False)
    op.create_index(op.f('ix_day_user_id'), 'day', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_day_user_id'), table_name='day')
    op.drop_index(op.f('ix_day_id'), table_name='day')
    op.drop_table('day')
    op.drop_index(op.f('ix_auth_token_id'), table_name='auth_token')
    op.drop_table('auth_token')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
